management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.github.courtandrey.cinegraph: INFO
